### ISSUE TITLE
Revisione file password.yml

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-infrastructure#81]
Rinominare `password.yml` in `secrets.yml` secondo questo schema:

```
 wai_database_credentials:
  wai-prod:
    root: changeme
    matomo-admin-username: matomo-admin
    matomo-admin-password: changeme
```

Questa modifica andrebbe effettuata per tutti i valori di tipo *username*.

_Originally posted by @giafar in https://github.com/pdavide/wai-infrastructure/pull/73_
